#!/usr/bin/env python3
"""Generate `firmware/p3_data.h` from the imported, hashed artifacts.

Everything the firmware needs that is *data* — the fifteen pinned base frames, the three
write envelopes, the 292 whitelisted addresses in canonical order — is generated here from
`phenotype_manifest.json` rather than transcribed, so the C side cannot drift from the
Python side by a typo. `tests/test_firmware_twin.py` regenerates and compares, so a stale
header is a test failure.

Pure host-side; nothing here touches a board.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

R = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(R / "host"))
import p3_gate as g  # noqa: E402
import p3_genome as gn  # noqa: E402


def render(manifest: dict) -> str:
    base, roles = g.gc.pinned_frames(manifest)
    targets = sorted(far for far, r in roles.items() if r == "target")
    envelopes = g.envelopes(manifest)
    flush_fars = [e["flush"] for e in envelopes]
    tindex = {far: i for i, far in enumerate(targets)}
    findex = {far: i for i, far in enumerate(flush_fars)}
    addresses = gn.addresses(manifest)

    out = [
        "/* GENERATED by host/gen_firmware_data.py — do not edit.",
        " *",
        " * Source: zynq-fabricmap phenotype_manifest.json",
        f" *   sha256 {hashlib.sha256(g.MANIFEST.read_bytes()).hexdigest()}",
        f" * Canonical address order digest: {gn.addresses_sha256(manifest)}",
        " *",
        " * The twelve target frames are the candidate's; the three flush frames are written",
        " * verbatim (the device's auto-increment reaches them after the four targets).",
        " */",
        "#ifndef P3_DATA_H",
        "#define P3_DATA_H",
        "#include <stdint.h>",
        "",
        f"#define P3_IDCODE 0x{g.wp.IDCODE_XC7Z010:08x}u",
        "",
        "static const uint32_t P3_TARGET_FARS[12] = {",
        "    " + ", ".join(f"0x{f:08x}u" for f in targets),
        "};",
        "static const uint32_t P3_FLUSH_FARS[3] = {",
        "    " + ", ".join(f"0x{f:08x}u" for f in flush_fars),
        "};",
        "",
        "/* envelope: FAR-set, the four target frames it carries (indices into P3_TARGET_FARS),",
        " * and the flush frame that follows them (index into P3_FLUSH_FARS). */",
        "typedef struct { uint32_t far_set; int target[4]; int flush; } p3_envelope;",
        "static const p3_envelope P3_ENVELOPE[3] = {",
    ]
    for e in envelopes:
        t = ", ".join(str(tindex[f]) for f in e["targets"])
        out.append(f"    {{ 0x{e['far_set']:08x}u, {{ {t} }}, {findex[e['flush']]} }},")
    out += [
        "};",
        "",
        "/* a whitelisted content bit: which target frame, which word, which bit.",
        " * Index i of this table is bit i of the genome (canonical ascending far/word/bit). */",
        "typedef struct { uint8_t frame; uint8_t word; uint8_t bit; } p3_address;",
        "static const p3_address P3_WHITELIST[292] = {",
    ]
    for far, w, b in addresses:
        out.append(f"    {{ {tindex[far]}, {w}, {b} }},")
    out += ["};", ""]

    def frame_block(name: str, fars: list[int]) -> list[str]:
        rows = [f"static const uint32_t {name}[{len(fars)}][101] = {{"]
        for far in fars:
            words = base[far]
            rows.append(f"    {{ /* {far:#010x} */")
            for i in range(0, 101, 6):
                rows.append("        " + " ".join(f"0x{w:08x}u," for w in words[i:i + 6]))
            rows.append("    },")
        rows.append("};")
        return rows

    out += frame_block("P3_BASE_TARGET", targets)
    out += [""]
    out += frame_block("P3_BASE_FLUSH", flush_fars)
    out += ["", "#endif /* P3_DATA_H */", ""]
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=R / "firmware/p3_data.h")
    ap.add_argument("--check", action="store_true", help="exit 1 if the file is stale")
    args = ap.parse_args(argv)
    text = render(g.load_manifest())
    if args.check:
        current = args.out.read_text() if args.out.exists() else ""
        if current != text:
            print(f"{args.out} is stale", file=sys.stderr)
            return 1
        print(f"{args.out} is current")
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    print(f"{args.out}: {len(text.splitlines())} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
