#!/usr/bin/env python3
"""Generate `firmware/p3_data.h` from the imported, hashed artifacts.

Everything the firmware needs that is *data* — the fifteen pinned base frames, the three
write envelopes, the 292 whitelisted addresses in canonical order, and (L6 §2.1) the
operator tables derived from the pinned `local_map.json` — is generated here from
`phenotype_manifest.json` and the map rather than transcribed, so the C side cannot drift
from the Python side by a typo. `tests/test_firmware_twin.py` regenerates and compares, so
a stale header is a test failure. The operator tables are `host/l6_operators.operator_data`
rendered as C, and the header carries that derivation's sha256 (`P3_OPERATOR_DATA_SHA256`),
which the image's IDENT names and the host regenerates and compares (prereg §2.1, §2.4).

Pure host-side; nothing here touches a board.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

R = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(R / "host"))
import p3_gate as g  # noqa: E402
import p3_genome as gn  # noqa: E402
import l6_operators as lo  # noqa: E402


def render(manifest: dict, local_map: dict | None = None) -> str:
    local_map = lo.load_local_map() if local_map is None else local_map
    base, roles = g.gc.pinned_frames(manifest)
    targets = sorted(far for far, r in roles.items() if r == "target")
    envelopes = g.envelopes(manifest)
    flush_fars = [e["flush"] for e in envelopes]
    tindex = {far: i for i, far in enumerate(targets)}
    findex = {far: i for i, far in enumerate(flush_fars)}
    addresses = gn.addresses(manifest)

    out = [
        "/* GENERATED by host/gen_firmware_data.py — do not edit.",
        " *",
        " * Source: zynq-fabricmap phenotype_manifest.json",
        f" *   sha256 {hashlib.sha256(g.MANIFEST.read_bytes()).hexdigest()}",
        f" * Canonical address order digest: {gn.addresses_sha256(manifest)}",
        f" * Operator data (local_map.json derivation) sha256: {lo.operator_data_sha256(lo.operator_data(manifest, local_map))}",
        " *",
        " * The twelve target frames are the candidate's; the three flush frames are written",
        " * verbatim (the device's auto-increment reaches them after the four targets).",
        " */",
        "#ifndef P3_DATA_H",
        "#define P3_DATA_H",
        "#include <stdint.h>",
        "",
        f"#define P3_IDCODE 0x{g.wp.IDCODE_XC7Z010:08x}u",
        "",
        "static const uint32_t P3_TARGET_FARS[12] = {",
        "    " + ", ".join(f"0x{f:08x}u" for f in targets),
        "};",
        "static const uint32_t P3_FLUSH_FARS[3] = {",
        "    " + ", ".join(f"0x{f:08x}u" for f in flush_fars),
        "};",
        "",
        "/* envelope: FAR-set, the four target frames it carries (indices into P3_TARGET_FARS),",
        " * and the flush frame that follows them (index into P3_FLUSH_FARS). */",
        "typedef struct { uint32_t far_set; int target[4]; int flush; } p3_envelope;",
        "static const p3_envelope P3_ENVELOPE[3] = {",
    ]
    for e in envelopes:
        t = ", ".join(str(tindex[f]) for f in e["targets"])
        out.append(f"    {{ 0x{e['far_set']:08x}u, {{ {t} }}, {findex[e['flush']]} }},")
    out += [
        "};",
        "",
        "/* a whitelisted content bit: which target frame, which word, which bit.",
        " * Index i of this table is bit i of the genome (canonical ascending far/word/bit). */",
        "typedef struct { uint8_t frame; uint8_t word; uint8_t bit; } p3_address;",
        "static const p3_address P3_WHITELIST[292] = {",
    ]
    for far, w, b in addresses:
        out.append(f"    {{ {tindex[far]}, {w}, {b} }},")
    out += ["};", ""]

    def frame_block(name: str, fars: list[int]) -> list[str]:
        rows = [f"static const uint32_t {name}[{len(fars)}][101] = {{"]
        for far in fars:
            words = base[far]
            rows.append(f"    {{ /* {far:#010x} */")
            for i in range(0, 101, 6):
                rows.append("        " + " ".join(f"0x{w:08x}u," for w in words[i:i + 6]))
            rows.append("    },")
        rows.append("};")
        return rows

    out += frame_block("P3_BASE_TARGET", targets)
    out += [""]
    out += frame_block("P3_BASE_FLUSH", flush_fars)
    out += [""] + operator_block(manifest, local_map)
    out += ["", "#endif /* P3_DATA_H */", ""]
    return "\n".join(out)


def operator_block(manifest: dict, local_map: dict) -> list[str]:
    """The two-operator image's map data (L6 prereg §2.1): each LUT's genome-bit indices in
    INIT-index order, the mutation size, and the sha256 of the derivation they come from."""
    data = lo.operator_data(manifest, local_map)
    keys = sorted(data["luts"])
    maxlen = max(len(data["luts"][k]) for k in keys)
    out = [
        "/* L6 two-operator image: the map data behind the map-guided operator, derived from the",
        f" * pinned local_map.json ({data['map_id']}) by host/l6_operators.py:operator_data.",
        " * P3_OPERATOR_DATA_SHA256 is that derivation's hash; the IDENT names it and the host",
        " * regenerates and compares it (prereg §2.1, §2.4). LUT order = sorted map keys. */",
        f'#define P3_OPERATOR_DATA_SHA256 "{lo.operator_data_sha256(data)}"',
        f"#define P3_MUTATION_BITS {data['mutation_bits']}",
        f"#define P3_LUT_COUNT {len(keys)}",
        f"#define P3_LUT_MAX_BITS {maxlen}",
        "static const char *const P3_LUT_KEYS[P3_LUT_COUNT] = {",
    ]
    out += [f'    "{k}",' for k in keys]
    out += ["};", "static const uint16_t P3_LUT_LEN[P3_LUT_COUNT] = {",
            "    " + ", ".join(str(len(data["luts"][k])) for k in keys), "};",
            "/* genome bit index of INIT position j of LUT i (INIT-index order); unused tail is 0xFFFF */",
            "static const uint16_t P3_LUT_BITS[P3_LUT_COUNT][P3_LUT_MAX_BITS] = {"]
    for k in keys:
        bits = [row["genome_bit"] for row in data["luts"][k]]
        bits += [0xFFFF] * (maxlen - len(bits))
        out.append("    { " + ", ".join(str(b) for b in bits) + " },")
    out += ["};"]
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=R / "firmware/p3_data.h")
    ap.add_argument("--check", action="store_true", help="exit 1 if the file is stale")
    args = ap.parse_args(argv)
    text = render(g.load_manifest())
    if args.check:
        current = args.out.read_text() if args.out.exists() else ""
        if current != text:
            print(f"{args.out} is stale", file=sys.stderr)
            return 1
        print(f"{args.out} is current")
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    print(f"{args.out}: {len(text.splitlines())} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
