#!/usr/bin/env python3
"""ARM-gate fixture for tb_p3_core.v, produced by the SAME signer the host will use.

Emits tb/arm_fixture.vh with: KEY_A, NONCE_SEED, the six LUT INITs (= the carrier's target
truth tables from carrier_constants.json, so a correct arm also scores TRAIN_COUNT/TRAIN_COUNT),
the nonce sequence n0..n2 (validators/nonce.py), and payload+tag words for each case.
"""
import hashlib, json, os, sys, tempfile
from pathlib import Path
R = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(R))
from validators import signer as sg, nonce as nn

KEY = bytes(range(16))                       # KEY_A of tb_p3_siphash (LE int 0x0f0e..00)
SEED = 0x9E3779B97F4A7C15
consts = json.load(open(R / "imported/fabricmap/vivado/carrier/generated/carrier_constants.json"))
INITS = [int(l["target"]) for l in consts["luts"]]        # six 64-bit targets
n = nn.sequence(SEED, 3)
tmp = Path(tempfile.mkdtemp()); kp = tmp / "K"; kp.write_bytes(KEY); os.chmod(kp, 0o400)
holder = sg.KeyHolder(kp)

def commit(label): return hashlib.sha256(label.encode()).digest()
def verdict(c): return {"writable": True, "candidate_sha256": c.hex()}
def words(p): return p.words()

cases = {}
c1, c2, c3, c4 = commit("cand1"), commit("cand2"), commit("cand3"), commit("cand4")
cases["VALID1"]      = words(sg.sign_arm(holder, verdict(c1), c1, INITS, n[0].to_bytes(8, "little")))
cases["VALID2"]      = words(sg.sign_arm(holder, verdict(c2), c2, INITS, n[1].to_bytes(8, "little")))
p = sg.sign_arm(holder, verdict(c1), c1, INITS, n[0].to_bytes(8, "little"))
cases["UNSIGNED"]    = words(sg.ArmPayload(p.candidate_commit, p.expected_tables, p.nonce, bytes(16)))
q = sg.sign_arm(holder, verdict(c3), c3, INITS, n[0].to_bytes(8, "little"))
cases["WRONG_COMMIT"] = words(sg.ArmPayload(c4, q.expected_tables, q.nonce, q.tag))   # tag for c3, payload says c4
bad_tables = [INITS[0] ^ 1] + INITS[1:]
cases["WRONG_TABLE"] = words(sg.sign_arm(holder, verdict(c1), c1, bad_tables, n[0].to_bytes(8, "little")))  # correctly signed, fabric differs

KEY_B = bytes(range(16, 32))
out = ["// generated by tb/gen_arm_fixture.py — do not edit",
       f"localparam [127:0] KEY_A = 128'h{int.from_bytes(KEY,'little'):032x};",
       f"localparam [127:0] KEY_B = 128'h{int.from_bytes(KEY_B,'little'):032x};",
       f"localparam [63:0] SEED = 64'h{SEED:016x};"]
out += [f"localparam [63:0] N{i} = 64'h{v:016x};" for i, v in enumerate(n)]
out += [f"localparam [63:0] INIT{i} = 64'h{v:016x};" for i, v in enumerate(INITS)]
for name, w in cases.items():
    assert len(w) == 24
    out.append(f"localparam [767:0] {name} = 768'h" + "".join(f"{x:08x}" for x in w) + ";")
out.append(f"localparam [255:0] C1 = 256'h{c1.hex()}; localparam [255:0] C2 = 256'h{c2.hex()};")
(R / "tb/arm_fixture.vh").write_text("\n".join(out) + "\n")
print("fixture:", list(cases), "nonces", [hex(x) for x in n])
